### ISSUE TITLE
Styles leaking into panel

### ISSUE THREAD

**Issue by nilshoerrmann** [moritzebeling/kirby-panel-button#2]
The panel button includes this line of CSS:

```css
p {
    margin-bottom: var(--spacing-2);
}
```

This is affacting styling across the panel and should be more specific, e. g. `.k-button-section p`.
